package on2014_12.on2014_12_26_Sudo_Code_2_0.ProblemsWithArray;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2014_12/on2014_12_26_Sudo_Code_2_0/ProblemsWithArray/ProblemsWithArray.task"))
			Assert.fail();
	}
}
