package on2012_10.on2012_10_21_Codeforces_Round__146__Div__1_.E___Number_Challenge;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2012_10/on2012_10_21_Codeforces_Round__146__Div__1_/E___Number_Challenge/E - Number Challenge.task"))
			Assert.fail();
	}
}
