package on2013_09.on2013_09_27_Code_War_2013.Two_Function_Conundrum;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2013_09/on2013_09_27_Code_War_2013/Two_Function_Conundrum/Two Function Conundrum.task"))
			Assert.fail();
	}
}
